/*
** BSGL Tutorial 11 - Using audio
** (adapted from the HGE 1.9 tutorial series)
**
** Demonstrates the three audio resource types and channel control:
**   Effect  - short sounds, a new channel per Effect_Play()
**   Stream  - long streamed audio, one channel per stream
**   Music   - module music (MOD/XM/...), loops like HGE's HMUSIC
**
** Keys:
**   SPACE    play the sound effect
**   S        play/stop the stream
**   M        play/stop the module music
**   UP/DOWN  slide the effect volume (Channel_SlideTo)
**   P        pan the effect left<->right
**   ESC      quit
**
** snd.wav, stream.wav and music.mod are generated by
** tutorials/res/gen_assets.py.
*/

#include "bsgl.h"

static BSGL* bsgl = nullptr;

static HEFFECT  snd   = 0;
static HSTREAM  strm  = 0;
static HMUSIC   mus   = 0;

static HCHANNEL snd_chn = 0;    // most recent effect channel
static HCHANNEL strm_chn = 0;
static HCHANNEL mus_chn = 0;

static int vol = 100;
static int pan = 0;

static bool KeyHeld(int key) {
    return bsgl->Control_IsDown(key) || bsgl->Control_IsPassing(key);
}

bool LogicFunc() {
    bsgl->Control_GetState();

    if (bsgl->Control_IsDown(INP_ESC)) {
        return true;
    }

    // fire a fresh sound effect; each play gets its own channel
    if (bsgl->Control_IsDown(INP_SPACE)) {
        snd_chn = bsgl->Effect_Play(snd);
        bsgl->Channel_SetPanning(snd_chn, pan);
    }

    if (bsgl->Control_IsDown(INP_S)) {
        if (strm_chn && bsgl->Channel_IsPlaying(strm_chn)) {
            bsgl->Channel_Stop(strm_chn);
        } else {
            strm_chn = bsgl->Stream_Play(strm);
        }
    }

    if (bsgl->Control_IsDown(INP_M)) {
        if (mus_chn && bsgl->Channel_IsPlaying(mus_chn)) {
            bsgl->Music_Stop(mus);
        } else {
            mus_chn = bsgl->Music_Play(mus);
        }
    }

    // slide the effect volume up/down over half a second
    if (KeyHeld(INP_UP))   { vol += 2; bsgl->Channel_SlideTo(snd_chn, 500, vol, -101, -1.0f); }
    if (KeyHeld(INP_DOWN)) { vol -= 2; bsgl->Channel_SlideTo(snd_chn, 500, vol, -101, -1.0f); }
    if (vol < 0)   vol = 0;
    if (vol > 100) vol = 100;

    // bounce the effect between the speakers
    if (bsgl->Control_IsDown(INP_P)) {
        pan = (pan == -100) ? 100 : -100;
        bsgl->Channel_SlideTo(snd_chn, 500, -1, pan, -1.0f);
    }

    return false;
}

bool RenderFunc() {
    bsgl->Gfx_BeginScene();
    bsgl->Gfx_Clear(0);

    // (audio has no visuals of its own; watch the speakers instead)

    bsgl->Gfx_EndScene();
    return false;
}

void bsgl_main() {
    bsgl = bsglCreate(BSGL_VERSION);

    bsgl->System_SetStateString(BSGL_LOGFILE, "tutorial11.log");
    bsgl->System_SetStateFunc(BSGL_LOGICFUNC, LogicFunc);
    bsgl->System_SetStateFunc(BSGL_RENDERFUNC, RenderFunc);
    bsgl->System_SetStateString(BSGL_TITLE, "BSGL Tutorial 11 - Using audio");

    bsgl->System_SetStateBool(BSGL_WINDOWED, true);
    bsgl->System_SetStateInt(BSGL_SCREENWIDTH, 800);
    bsgl->System_SetStateInt(BSGL_SCREENHEIGHT, 600);

    if (bsgl->System_Initiate()) {
        snd  = bsgl->Effect_Load("snd.wav");
        strm = bsgl->Stream_Load("stream.wav");
        mus  = bsgl->Music_Load("music.mod");
        if (!snd || !strm || !mus) {
            bsgl->System_Log("Error: can't load audio resources"
                             " (run tutorials/res/gen_assets.py)");
            bsgl->System_Shutdown();
            bsgl->Release();
            return;
        }

        // the stream starts playing immediately, like HGE background music
        strm_chn = bsgl->Stream_Play(strm);

        bsgl->System_Start();

        bsgl->Effect_Free(snd);
        bsgl->Stream_Free(strm);
        bsgl->Music_Free(mus);

        bsgl->System_Shutdown();
    } else {
        bsgl->System_Log("Error: %s", bsgl->System_GetErrorMessage());
    }

    bsgl->Release();
}
