/*
** BSGL Tutorial 02 - Using input and rendering
** (adapted from hge_tut02 - Using input, sound and rendering)
**
** Move the orb with the arrow keys; it bounces off the window edges.
** Click the left mouse button to teleport it to the cursor.
** Press ESC to quit.
**
** The bsglQuad is the basic primitive in BSGL used for rendering
** graphics. A quad contains 4 vertices, numbered 0 to 3 clockwise.
*/

#include "bsgl.h"

static BSGL* bsgl = 0;

// The quad we will render
static bsglQuad quad;

// Some "gameplay" variables and constants
static float x = 100.0f, y = 100.0f;
static float dx = 0.0f, dy = 0.0f;

static const float speed    = 90;
static const float friction = 0.98f;

// Control_IsDown() reports a key only on the frame it is pressed,
// Control_IsPassing() only while it keeps being held. For continuous
// movement we want both.
static bool KeyHeld(int key) {
    return bsgl->Control_IsDown(key) || bsgl->Control_IsPassing(key);
}

bool LogicFunc() {
    // Get the time elapsed since the last call of LogicFunc().
    // This helps to synchronize movement on different machines.
    float dt = bsgl->Timer_GetDelta();

    // Sample keyboard and mouse state for this frame
    bsgl->Control_GetState();

    // Process keys
    if( bsgl->Control_IsDown(INP_ESC) ) {
        return true;
    }
    if( KeyHeld(INP_LEFT)  ) dx -= speed*dt;
    if( KeyHeld(INP_RIGHT) ) dx += speed*dt;
    if( KeyHeld(INP_UP)    ) dy -= speed*dt;
    if( KeyHeld(INP_DOWN)  ) dy += speed*dt;

    // Teleport to the mouse cursor on left click
    if( bsgl->Control_IsDown(INP_MOUSEL) ) {
        x = (float)bsgl->Control_GetMouseX();
        y = (float)bsgl->Control_GetMouseY();
        dx = dy = 0.0f;
    }

    // Do some movement calculations and collision detection
    dx *= friction;
    dy *= friction;
    x += dx;
    y += dy;
    if( x > 784 ) { x = 784 - (x-784); dx = -dx; }
    if( x < 16  ) { x = 16 + 16 - x;   dx = -dx; }
    if( y > 584 ) { y = 584 - (y-584); dy = -dy; }
    if( y < 16  ) { y = 16 + 16 - y;   dy = -dy; }

    // Set up the quad's screen coordinates
    quad.v[0].x = x-16; quad.v[0].y = y-16;
    quad.v[1].x = x+16; quad.v[1].y = y-16;
    quad.v[2].x = x+16; quad.v[2].y = y+16;
    quad.v[3].x = x-16; quad.v[3].y = y+16;

    // Continue execution
    return false;
}

// This function will be called by BSGL when
// the application window should be redrawn.
// Put your rendering code here.
bool RenderFunc() {
    // Begin rendering. This function must be
    // called before any actual rendering.
    bsgl->Gfx_BeginScene();

    // Clear the screen with black color
    bsgl->Gfx_Clear(0);

    // Render quads here. This time just
    // one of them will serve our needs.
    bsgl->Gfx_RenderQuad(&quad);

    // End rendering and update the screen
    bsgl->Gfx_EndScene();

    // RenderFunc should always return false
    return false;
}

void bsgl_main() {
    // Get the BSGL interface
    bsgl = bsglCreate(BSGL_VERSION);

    // Set up log file, logic function, render function and window title
    bsgl->System_SetStateString(BSGL_LOGFILE, "tutorial02.log");
    bsgl->System_SetStateFunc(BSGL_LOGICFUNC, LogicFunc);
    bsgl->System_SetStateFunc(BSGL_RENDERFUNC, RenderFunc);
    bsgl->System_SetStateString(BSGL_TITLE, "BSGL Tutorial 02 - Using input and rendering");

    // Set up video mode
    bsgl->System_SetStateBool(BSGL_WINDOWED, true);
    bsgl->System_SetStateInt(BSGL_SCREENWIDTH, 800);
    bsgl->System_SetStateInt(BSGL_SCREENHEIGHT, 600);

    if( bsgl->System_Initiate() ) {
        // Load the texture. BSGL loads uncompressed 32-bit BMP files;
        // sprite.bmp is generated by tutorials/res/gen_assets.py.
        quad.tex = bsgl->Texture_Load("sprite.bmp");
        if( !quad.tex ) {
            // If the data file is not found, log an error and shutdown.
            bsgl->System_Log("Error: can't load sprite.bmp");
            bsgl->System_Shutdown();
            bsgl->Release();
            return;
        }

        // Set up the quad which we will use for rendering:
        // additive blending makes the orb glow
        quad.blend = BLEND_COLORMUL | BLEND_ALPHAADD | BLEND_NOZWRITE;

        for( int i=0; i<4; ++i ) {
            // Set up z-coordinate of vertices
            quad.v[i].z = 0.5f;
            // Set up color, tint the orb orange
            quad.v[i].color = RGBA(0xFF, 0xA0, 0x00, 0xFF);
        }

        // Set up the quad's texture coordinates.
        // 0,0 means top left corner and 1,1 -
        // bottom right corner of the texture.
        quad.v[0].tx = 0.0f; quad.v[0].ty = 0.0f;
        quad.v[1].tx = 1.0f; quad.v[1].ty = 0.0f;
        quad.v[2].tx = 1.0f; quad.v[2].ty = 1.0f;
        quad.v[3].tx = 0.0f; quad.v[3].ty = 1.0f;

        // Let's rock now!
        bsgl->System_Start();

        // Free the loaded texture
        bsgl->Texture_Free(quad.tex);

        bsgl->System_Shutdown();
    }else {
        bsgl->System_Log("Error: %s", bsgl->System_GetErrorMessage());
    }

    // Clean up and shutdown
    bsgl->Release();
}
